name: thor_ui
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  thor:
    path: ../thor

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
  test: ^1.25.6
