name: thor
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
  test: ^1.25.6
